In [45]:
import numpy as np

1.Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [46]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [47]:
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [48]:
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [49]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [50]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [51]:
np.cov(zp, ks, ddof=0)[0,1]

9157.840000000002

In [52]:
np.cov(zp, ks)[0,1]

10175.377777777778

In [53]:
ks.std(ddof=0)

174.55340157098058

In [54]:
zp.std(ddof=0)

59.115480206118605

In [55]:
ks.std()

174.55340157098058

In [56]:
zp.std()

59.115480206118605

In [57]:
#  коэффициент корреляции Пирсона
np.cov(zp, ks)[0,1] / (ks.std(ddof=0) * zp.std(ddof=0))

0.9861001023043512

In [58]:
#  коэффициент корреляции Пирсона
np.cov(zp, ks, ddof=0)[0,1] / (ks.std() * zp.std())

0.8874900920739163

2.Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [59]:
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
IQ

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [60]:
t = 2.262
n = 10

In [61]:
IQ.mean() - (t * IQ.std(ddof=1)/(n)**0.5)

110.55660776308164

In [62]:
IQ.mean() + (t * IQ.std(ddof=1)/(n)**0.5)

125.64339223691834

3.Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [63]:
D = 25
n = 27
mu = 174.2
alfa = 5

In [64]:
std = D**0.5
std

5.0

In [65]:
Z = 1.96

In [66]:
mu - (Z * std/(n)**0.5)

172.31398912064722

In [67]:
mu + (Z * std/(n)**0.5)

176.08601087935276

In [69]:
# [172.31398912064722; 176.08601087935276]