In [62]:
import numpy as np



1.Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга
 (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
 Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак),
 а за y - значения скорингового балла (то есть, ks - целевая переменная).
 Произвести расчет как с использованием intercept, так и без.



In [63]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [64]:
n = 10

$$b = \frac{\overline{yx} - \overline{y} \cdot {\overline{x}}}{\overline{x^2} - (\overline{x})^2};$$

$$a = \overline{y} - b \cdot {\overline{x}}.$$

In [65]:
# Для нахождения коэффициентов регрессии  𝑎  и  𝑏  
b = (np.mean(zp * ks) - np.mean(zp) * np.mean(ks)) / (np.mean(zp**2) - np.mean(zp) ** 2)
b

2.620538882402765

In [66]:
a = np.mean(ks) - b * np.mean(zp)
a

444.1773573243596

In [67]:
X = zp.reshape((10,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [68]:
y = ks.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [69]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)),X.T @ y)
B

array([[5.88982042]])

2.Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

 

In [70]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = 10

In [71]:
def mse_(B1,y=ks,X=zp,n=10):
    return np.sum((B1*X-y)**2)/n

In [72]:
B1 = 0.1

In [73]:
alfa = 5e-5

In [80]:
for i in range (10000):
    B1 -= alfa*(2/n)*np.sum((B1*X-y)*X)
    if i%2000==0:
        print(f'Iteration {i}, B1={B1}, mse = {mse_(B1)}')

Iteration 0, B1=5.889820420132688, mse = 56516.8584157194
Iteration 2000, B1=5.889820420132688, mse = 56516.8584157194
Iteration 4000, B1=5.889820420132688, mse = 56516.8584157194
Iteration 6000, B1=5.889820420132688, mse = 56516.8584157194
Iteration 8000, B1=5.889820420132688, mse = 56516.8584157194
